name: AdminMode
version: ${project.version}
description: ${project.description}
authors: [ bermudalocket ]
main: com.bermudalocket.adminmode.AdminMode
depend: [LuckPerms, Citizens]

api-version: 1.17

commands:
  modmode:
    description: Toggle ModMode
    permission: modmode.toggle
    aliases:
      - adminmode

permissions:
  modmode:
    description: Allow the player to enter ModMode
