name: Maven CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2.3.4
    - name: init java 16
      uses: actions/setup-java@v2.3.0
      with:
        java-version: 16
        distribution: adopt-hotspot
    - name: maven
      run: mvn clean package
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: artifact
        path: target/
